config:
  plugins:
    metrics-by-endpoint: {}
  target: 'http://127.0.0.1:8080'
  phases:
    - duration: 20
      arrivalRate: 10
scenarios:
  - name: "Sessions Flow (register + login)"
    flow:
      - log: 'Creating variables for users'
      - get:
          url: '/api/test/user'
          capture:
            - json: "$.first_name"
              as: "first_name"
            - json: "$.last_name"
              as: "last_name"
            - json: "$.email"
              as: "email"
            - json: "$.password"
              as: "password"
      - log: "Registering User"
      - post:
          url: '/api/session/register'
          json:
            first_name: "{{ first_name }}"
            last_name: "{{ last_name }}"
            email: "{{ email }}"
            password: "{{ password }}"
      - think: 2
      - log: "Login User"
      - post:
          url: '/api/session/login'
          json:
            email: "{{ email }}"
            password: "{{ password }}"